# Generated by Django 5.2.5 on 2025-08-09 03:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
                "db_table": "Admins",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "Departments",
            },
        ),
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time_block_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "batch_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Time Block",
                "verbose_name_plural": "Time Blocks",
                "db_table": "TimeBlocks",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Academic year (1-4)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        db_column="dept_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "Batches",
                "unique_together": {("dept", "year")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                ("section_name", models.CharField(max_length=10)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "Sections",
                "unique_together": {("batch", "section_name")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("register_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Face recognition embedding data",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "Students",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_code", models.CharField(max_length=20, unique=True)),
                ("subject_name", models.CharField(max_length=200, unique=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Academic year (1-4)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        db_column="dept_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "Subjects",
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timetable_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "db_table": "Timetable",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        db_column="timetable_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "Attendance",
                "unique_together": {("student", "timetable")},
            },
        ),
    ]
