# Generated by Django 5.2.5 on 2025-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
                "db_table": "Admins",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dept_id",
                    models.IntegerField(
                        help_text="Department ID (manually assigned)",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dept_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "batch_year",
                    models.PositiveIntegerField(
                        help_text="Graduation year (e.g., 2027, 2028)"
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        db_column="dept_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "Batches",
                "unique_together": {("dept", "batch_year")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                ("section_name", models.CharField(max_length=10)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "db_table": "Sections",
                "unique_together": {("batch", "section_name")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_regno",
                    models.CharField(
                        help_text="Student registration number",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "section",
                    models.CharField(
                        help_text="Section name (A, B, C, etc.)", max_length=10
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.batch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="dept_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "Students",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_code", models.CharField(max_length=20, unique=True)),
                ("subject_name", models.CharField(max_length=200, unique=True)),
                (
                    "batch",
                    models.ForeignKey(
                        db_column="batch_id",
                        help_text="Batch this subject is applicable to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.batch",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        help_text="Departments that offer this subject",
                        related_name="subjects",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "Subjects",
            },
        ),
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time_block_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "batch_year",
                    models.PositiveIntegerField(
                        help_text="Graduation year (e.g., 2025, 2026, 2027, 2028) or 0 for all batches"
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Time Block",
                "verbose_name_plural": "Time Blocks",
                "db_table": "TimeBlocks",
                "unique_together": {("batch_year", "block_number")},
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timetable_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "db_table": "Timetable",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_regno",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        db_column="timetable_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "Attendance",
                "unique_together": {("student", "timetable")},
            },
        ),
    ]
