# Generated by Django 5.2.5 on 2025-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="batch",
            name="batch_year",
            field=models.PositiveIntegerField(
                default=2027, help_text="Graduation year (e.g., 2027, 2028)"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("dept", "year", "batch_year")},
        ),
    ]
