# Generated by Django 5.2.5 on 2025-08-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="embedding",
            field=models.BinaryField(
                blank=True, help_text="Face recognition embedding data", null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.ForeignKey(
                db_column="section_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.section",
            ),
        ),
    ]
