# Generated by Django 5.2.5 on 2025-08-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_student_embedding_alter_student_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="embedding",
        ),
    ]
