# Generated by Django 5.2.5 on 2025-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_batch_unique_together_batch_batch_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("dept", "batch_year")},
        ),
        migrations.AlterField(
            model_name="department",
            name="dept_id",
            field=models.IntegerField(
                help_text="Department ID (manually assigned)",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="batch",
            name="year",
        ),
    ]
