# Generated by Django 5.2.5 on 2025-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_batch_unique_together_alter_department_dept_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="dept",
        ),
        migrations.AddField(
            model_name="subject",
            name="departments",
            field=models.ManyToManyField(
                help_text="Departments that offer this subject",
                related_name="subjects",
                to="core.department",
            ),
        ),
    ]
