# Generated by Django 5.2.5 on 2025-09-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_embedding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('section', 'subject', 'date', 'start_time', 'end_time')},
        ),
    ]
