# Generated by Django 5.2.5 on 2025-09-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Department that created/owns this subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_subjects', to='core.department'),
        ),
    ]
