# Generated by Django 5.2.5 on 2025-09-04 15:00
# Manual migration to fix Subject-Department many-to-many relationship

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- This migration represents the manual fixes applied to resolve
            -- the missing Subjects_departments table issue.
            -- The operations were already performed manually:
            -- 1. Created Subjects_departments table
            -- 2. Migrated data from dept_id column to many-to-many table
            -- 3. Removed dept_id column from Subjects table
            SELECT 1; -- No-op since changes were already applied
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
