# Generated by Django 5.2.5 on 2025-08-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_subject_many_to_many_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="batch_year",
            field=models.PositiveIntegerField(
                help_text="Graduation year (e.g., 2025, 2026, 2027, 2028) or 0 for all batches"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeblock",
            unique_together={("batch_year", "block_number")},
        ),
    ]
