# Generated by Django 5.2.5 on 2025-08-10 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_student_embedding_alter_student_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("can_take_attendance", models.BooleanField(default=True)),
                ("can_view_all_attendance", models.BooleanField(default=True)),
                ("can_edit_attendance", models.BooleanField(default=True)),
                ("can_generate_reports", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("office_location", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific batches this advisor is responsible for",
                        related_name="advisors",
                        to="core.batch",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Departments this advisor is responsible for",
                        related_name="advisors",
                        to="core.department",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific sections this advisor is responsible for",
                        related_name="advisors",
                        to="core.section",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Advisor",
                "verbose_name_plural": "Advisors",
                "db_table": "advisor_profiles",
            },
        ),
    ]
