# Generated by Django 5.2.5 on 2025-09-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_users', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_advisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Creator',
                'verbose_name_plural': 'Staff Creators',
                'db_table': 'StaffCreators',
            },
        ),
    ]
